version: '2'
services:
#  api:
#    build: 
#      context: ./ 
#      dockerfile: ./api/Dockerfile
#    restart: always 
#    networks:
#      - default
  web:
    build:  
      context: ./ 
      dockerfile: ./web/Dockerfile 
    restart: always 
    networks:
      - neco_link

networks:
  neco_link:
    external: true
