export const view ={
  elements:{
    body: document.body,
    header: document.getElementsByTagName("header")[0],
    mainMenu: document.querySelectorAll("nav.mainMenu > ul > li"),
      new: document.getElementById("new"),
      open: document.getElementById("open"),
      openFile: document.getElementById("openFile"),
      close: document.getElementById("close"),
      closeAll: document.getElementById("closeAll"),
      save: document.getElementById("save"),
      saveAs: document.getElementById("saveAs"),
      import: document.getElementById("import"),
      importFile: document.getElementById("importFile"),
      export: document.getElementById("export"),
      print: document.getElementById("print"),
      printPreview: document.getElementById("printPreview"),
      exit: document.getElementById("exit"),
    main: document.getElementsByTagName("main")[0],
    toolBar: document.getElementsByClassName("toolBar")[0],
      run: document.getElementById("run"),
    contents: document.getElementsByClassName("contents")[0],
    aside: document.getElementsByTagName("aside")[0],
      drawmenu: document.querySelectorAll("aside.drawmenu>article>section"),
        line: document.getElementById("line"),
        polyline: document.getElementById("polyline"),
        circle: document.getElementById("circle"),
        rectangle: document.getElementById("rectangle"),
        point: document.getElementById("point"),
        resize: document.getElementById("resize"),
        filet: document.getElementById("filet"),
        chamfer: document.getElementById("chamfer"),
        copy: document.getElementById("copy"),
        move: document.getElementById("move"),
        divide: document.getElementById("divide"),
        vertical: document.getElementById("vertical"),
        horizontal: document.getElementById("horizontal"),
        parallel: document.getElementById("parallel"),
        rightangle: document.getElementById("rightangle"),
        coincident: document.getElementById("coincident"),
    property: document.getElementsByClassName("property")[0],
    maincontents: document.getElementsByClassName("maincontents")[0],
    drawing: document.getElementById("drawing"),
    slidebar: document.getElementById("slidebar"),
    scripting: document.getElementsByClassName("scripting")[0],
    footer: document.getElementsByTagName("footer")[0],
      coordinate:document.querySelector("footer>section>small"),
    tempElement: null,
    activeDrawElement: null,
  },
}
